"""Tests for tools/setup.py: first-run setup and its check. Synthetic fixtures only; every run passes --config so a
real config.json is never read or written.  Run from the skill folder:  python -m unittest discover -s tests
"""
import json
import os
import subprocess
import sys
import tempfile
import unittest
from datetime import date
from pathlib import Path

TOOLS = Path(__file__).resolve().parent.parent / "tools"
sys.path.insert(0, str(TOOLS))
import due  # noqa: E402
import pa_widget  # noqa: E402
from widget_store import Store  # noqa: E402

ENV = {"PYTHONIOENCODING": "utf-8", "SYSTEMROOT": os.environ.get("SYSTEMROOT", "")}


class Base(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp = Path(self._tmp.name)
        self.cfg_path = self.tmp / "config.json"     # stands in for the skill folder's config.json
        self.data = self.tmp / "pa-data"

    def tearDown(self):
        self._tmp.cleanup()

    def run_tool(self, script, *args):
        r = subprocess.run([sys.executable, str(TOOLS / script), "--config", str(self.cfg_path), *args],
                           capture_output=True, text=True, encoding="utf-8", env=ENV, timeout=20)
        return r.returncode, r.stdout + r.stderr

    def init(self, *extra):
        return self.run_tool("setup.py", "init", "--data-root", str(self.data), "--area", "home=Household and admin",
                             "--area", "study=Courses and exams", "--assistant-name", "Robin", "--chase-days", "10",
                             *extra)

    def snapshot(self):
        return {p.relative_to(self.tmp).as_posix(): p.read_bytes() for p in self.tmp.rglob("*") if p.is_file()}


class TestInit(Base):
    def test_fresh_setup_creates_a_working_data_folder(self):
        code, out = self.init()
        self.assertEqual(code, 0, out)
        for rel in ["config.json", "pa-data/pa.local.json", "pa-data/pa-local.md", "pa-data/CLAUDE.md",
                    "pa-data/index.md", "pa-data/home/tasks.md", "pa-data/home/done.md", "pa-data/home/about.md",
                    "pa-data/study/tasks.md", "pa-data/study/done.md", "pa-data/study/about.md"]:
            self.assertTrue((self.tmp / rel).is_file(), rel)
        self.assertEqual(Path(json.loads(self.cfg_path.read_text(encoding="utf-8"))["data_root"]), self.data)
        local = json.loads((self.data / "pa.local.json").read_text(encoding="utf-8"))
        self.assertEqual(local["areas"], [{"path": "home"}, {"path": "study"}])      # order kept
        self.assertEqual((local["assistant_name"], local["chase_days"], local["local_rules"]), ("Robin", 10, "pa-local.md"))
        self.assertEqual(local["links"], [])                                          # no example links carried over
        tasks = (self.data / "home" / "tasks.md").read_text(encoding="utf-8")
        self.assertTrue(tasks.startswith("# Tasks — home\n"))
        self.assertIn("**Do not edit this file.**", tasks)
        self.assertIn(f"Last reviewed: {date.today().isoformat()}", tasks)
        self.assertNotIn("- [", tasks)                                                # no example tasks
        self.assertTrue((self.data / "study" / "done.md").read_text(encoding="utf-8").startswith("# Done — study\n"))
        self.assertIn("# study — Courses and exams", (self.data / "study" / "about.md").read_text(encoding="utf-8"))
        self.assertIn("Default 10 days", (self.data / "pa-local.md").read_text(encoding="utf-8"))
        self.assertIn("| home | Household and admin |", (self.data / "index.md").read_text(encoding="utf-8"))
        # the rest of the skill works on it straight away
        code, out = self.run_tool("setup.py", "check")
        self.assertEqual(code, 0, out)
        self.assertIn("Setup complete.", out)
        self.assertNotIn("--", out)                                                   # no suggestions either
        code, out = self.run_tool("due.py")
        self.assertEqual(code, 0, out)
        self.assertNotIn("!", out.replace("! home: tasks.md", ""))
        cfg = due.settings(self.data, {"data_root": str(self.data)})
        data = pa_widget.build_data(self.data, cfg, Store(self.data))
        self.assertEqual(data["setup_problems"], [])
        self.assertEqual(data["assistant_name"], "Robin")

    def test_rerun_changes_nothing_and_never_overwrites(self):
        self.init()
        (self.data / "home" / "tasks.md").write_text("# Tasks — home\n- [ ] Mine | id:abc1\n", encoding="utf-8")
        (self.data / "pa-local.md").write_text("my own rules\n", encoding="utf-8")
        before = self.snapshot()
        code, out = self.init()
        self.assertEqual(code, 0, out)
        self.assertIn("Nothing to create.", out)
        self.assertEqual(self.snapshot(), before)

    def test_fills_gaps_and_names_unlisted_areas(self):
        self.init()
        (self.data / "home" / "done.md").unlink()
        code, out = self.run_tool("setup.py", "init", "--data-root", str(self.data), "--area", "home",
                                  "--area", "garden=Beds and trees")
        self.assertEqual(code, 0, out)
        self.assertTrue((self.data / "home" / "done.md").is_file())
        self.assertTrue((self.data / "garden" / "tasks.md").is_file())
        self.assertIn('add these areas to its "areas" list yourself: garden', out)
        local = json.loads((self.data / "pa.local.json").read_text(encoding="utf-8"))
        self.assertEqual([a["path"] for a in local["areas"]], ["home", "study"])     # untouched

    def test_dry_run_writes_nothing(self):
        code, out = self.init("--dry-run")
        self.assertEqual(code, 0, out)
        self.assertIn("would create", out)
        self.assertEqual(self.snapshot(), {})

    def test_refusals(self):
        code, out = self.run_tool("setup.py", "init", "--data-root", str(TOOLS.parent / "my-data"), "--area", "home")
        self.assertEqual(code, 2)
        self.assertIn("outside the skill folder", out)
        self.assertFalse((TOOLS.parent / "my-data").exists())
        code, out = self.run_tool("setup.py", "init", "--data-root", str(self.data), "--area", "../escape")
        self.assertEqual(code, 2)
        self.assertIn("letters, digits", out)
        code, out = self.run_tool("setup.py", "init", "--data-root", str(self.data), "--area", "a", "--area", "a")
        self.assertEqual(code, 2)
        self.cfg_path.write_text(json.dumps({"data_root": str(self.tmp / "elsewhere")}), encoding="utf-8")
        code, out = self.init()
        self.assertEqual(code, 2)
        self.assertIn("already points at", out)
        self.assertFalse(self.data.exists())


class TestCheck(Base):
    def test_missing_config(self):
        code, out = self.run_tool("setup.py", "check")
        self.assertEqual(code, 1)
        self.assertIn("no config file at", out)

    def test_reports_problems_and_suggestions(self):
        self.init()
        (self.data / "study" / "done.md").unlink()
        (self.data / "study" / "about.md").unlink()
        (self.data / "pa-local.md").unlink()
        (self.data / "CLAUDE.md").unlink()
        code, out = self.run_tool("setup.py", "check", "--json")
        self.assertEqual(code, 1)
        report = json.loads(out)
        self.assertIn("area study: no done.md", report["problems"])
        self.assertIn("local rules file pa-local.md (local_rules) is missing", report["problems"])
        self.assertIn("area study: no about.md (scope, key facts, standing decisions)", report["suggestions"])
        self.assertTrue(any("CLAUDE.md" in s for s in report["suggestions"]))
        cfg = due.settings(self.data, {"data_root": str(self.data)})
        gaps = pa_widget.build_data(self.data, cfg, Store(self.data))["setup_problems"]
        self.assertIn("area study: no done.md", gaps)                     # the widget's "setup incomplete" note


if __name__ == "__main__":
    unittest.main()
